### ISSUE TITLE
Unnecessary dependencies

### ISSUE THREAD

**Issue by raulmatei** [lmcq/fiql-query-builder#1]
Hi,

Thanks for this awesome module. We've tried to use it and it works seamlessly for us. The only problem we've had was when using it on the build machine where we have an older version of Node, we get this error: `error joi@13.4.0: The engine "node" is incompatible with this module. Expected version ">=8.9.0".`. 

Ok, this is not directly related to your module but on how you listed the dependencies in your `package.json`. Both `codacy-coverage` and `mocha-lcov-reporter` seem to be added as `dependencies` and not `devDependencies`.

**Comment by lmcq** [comment]
Hi,

This has been fixed in version 1.0.8
